### ISSUE TITLE
Does not work on Windows 11 Beta 22000.120

### ISSUE THREAD

**Issue by waldimen** [zgdump/windows-virtualdesktopindicator#1]
The app does not work on Windows 11 Beta. It just shows many messages saying: "An unhandled error occured".

Any chances to make it work on Windows 11 in the future?

**Comment by Flaflo** [comment]
> 
> 
> The app does not work on Windows 11 Beta. It just shows many messages saying: "An unhandled error occured".
> 
> Any chances to make it work on Windows 11 in the future?

Haven't got a chance to look at Windows 11 in person but I will definetly add support for it.
Unless @zgdump has already planned something else?

**Comment by zgdump** [comment]
Hello! Sorry, I missed the issue due to the workload. Yes, I will support Windows 11.
I'm plan fix crashes of Windows 11, hi dpi fuzziness and bugs when crashes explorer.exe. And try to implement the indication directly on the multitask button

Should be in time for the release of Windows 11 :)

**Comment by zgdump** [comment]
You have lifted my mood, I'll go and update Windows 11 to the latest Insider build
