### ISSUE TITLE
hello from windows 95

### ISSUE THREAD

**Issue by Hardtmuth** [zgdump/windows-virtualdesktopindicator#4]
Hi, I have an error with app in Windows 11 "an unhandled error occurred"

![indicator_error_](https://user-images.githubusercontent.com/23229721/147196367-765d633e-a20c-4fe1-a489-7c379e70db51.gif)

**Comment by zgdump** [comment]
Hello! Yes, this is a known problem related to the explorer. All hands will not reach to fix it once and for all...
