### ISSUE TITLE
Option to show Desktop Name

### ISSUE THREAD

**Issue by dflock** [zgdump/windows-virtualdesktopindicator#5]
It would be very nice to be able to see the desktop name, somehow.

Suggestion for how it could be shown, in order of (my) preference:

- As an on screen tooltip/toast/notification when you switch desktop, which goes away on it's own in a second or two
- In the taskbar: desktop number - desktop name, or just desktop name
- as a tooltip on hover of the taskbar icon

Thanks for the super useful virtualdesktop indicator - makes virtual desktops on windows much more useable!

**Comment by Flaflo** [comment]
![](https://user-images.githubusercontent.com/12973684/151722951-8bafbd4f-3e78-4142-bf3a-0b0b3e97c8d4.png)

Would this be sufficient?

**Comment by zgdump** [comment]
> Would this be sufficient? (GIF)

You beat me to it! As soon as there was time to programming project, I already see a gif of someone else's work) Thank you, @Flaflo
