### ISSUE TITLE
Click icon to show the Task View screen

### ISSUE THREAD

**Issue by dflock** [zgdump/windows-virtualdesktopindicator#8]
If clicking the virtualdesktop-indicator button did the same a clicking the Task View button - i.e. showed the built in Task View screen, then I could hide the Task View button and just have one desktop management button on the taskbar instead of two.

**Comment by Flaflo** [comment]
In my PR I implemented a this behavior on double click, do you think this is good or would you prefer a single click?

**Comment by dflock** [comment]
Thanks!

Given that single-click currently doesn't do anything, I thini I would prefer this work just like the built-in Task View button - i.e. show the Task View screen on single click. That way it's a drop-in replacement for the Task View button.

**Comment by Flaflo** [comment]
Done!
